# Generated by Django 3.1.2 on 2020-12-23 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201223_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(default='cook.jpeg', upload_to='room images'),
        ),
        migrations.AlterField(
            model_name='bookingorder',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 16, 16, 36, 773758)),
        ),
        migrations.AlterField(
            model_name='bookingorder',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 16, 16, 36, 773758)),
        ),
    ]
