# Generated by Django 2.2 on 2020-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200430_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profilepic',
            field=models.ImageField(default='', upload_to='staff images'),
        ),
    ]
