# Generated by Django 3.1.2 on 2020-12-23 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201223_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorder',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 20, 17, 44, 556456)),
        ),
        migrations.AlterField(
            model_name='bookingorder',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 20, 17, 44, 556456)),
        ),
    ]
