# Generated by Django 3.1.2 on 2020-12-23 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201223_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorder',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 20, 29, 33, 72924)),
        ),
        migrations.AlterField(
            model_name='bookingorder',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 20, 29, 33, 72924)),
        ),
    ]
