# Generated by Django 2.2 on 2020-05-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_booking_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
    ]
