# Generated by Django 2.2 on 2020-06-04 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_booking_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
