# Generated by Django 2.2 on 2020-06-04 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20200604_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
