# Generated by Django 2.2 on 2020-10-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_room_specifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
