# Generated by Django 2.2 on 2020-10-23 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('from_date', models.DateTimeField(default=datetime.date.today)),
                ('to_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
    ]
